### ISSUE TITLE
How to loop over all the pieces?

### ISSUE THREAD

**Issue by LouieMartin** [notnil/chess#123]
I was looking on how to loop for all the pieces like:
```go
for _, piece := range position.Pieces() {
  // logic
}
```

**Comment by jpope6** [comment]
My solution to looping through all the pieces was to use the 'SquareMap'. 
According to the documentation: "SquareMap returns a mapping of squares to pieces. A square is only added to the map if it is occupied."

```go
squareMap := game.Position().Board().SquareMap()

for square, piece := range squareMap {
    // logic
}
```
