### ISSUE TITLE
Annotation Support

### ISSUE THREAD

**Issue by notnil** [notnil/chess#13]

**Comment by notnil** [comment]
We need support for:
- Decoding annotations from PGN files and storing them in the data model
- Editing Annotations
- Encoding annotations into PGN export

**Comment by tysmithnet** [comment]
I wrote [this ANTRL grammar](https://github.com/tysmithnet/enhanced-pgn-parser) for parsing pgn databases that contain comments, block comments, nested alternate lines, and commands (like arrows and time markers). If you are interested I can create a go package for it and take a crack at integrating it.

**Comment by notnil** [comment]
Sure.  That could standardize it a bit.  Related reading for go:
https://blog.gopheracademy.com/advent-2017/parsing-with-antlr4-and-go/

**Comment by jvsteiner** [comment]
Would this enhancement mean that this library could support PGN files with variations?  I noticed that currently, it does not.

**Comment by notnil** [comment]
Variations would be a nice feature but its not on the roadmap.

**Comment by notnil** [comment]
Added in #76
