### ISSUE TITLE
50-move draw is using 50-half moves, not 50-moves

### ISSUE THREAD

**Issue by glinscott** [notnil/chess#16]
Eg. `8/8/8/8/4k3/8/3K2p1/5r2 w - - 50 119` should not be a draw, but is with the current rules.

Quote from wikipedia on this:
> The fifty-move rule in chess states that a player can claim a draw if no capture has been made and no pawn has been moved in the last fifty moves (for this purpose a "move" consists of a player completing their turn followed by the opponent completing their turn).

**Comment by notnil** [comment]
Fixed in #17
