### ISSUE TITLE
Algebratic notation should not have e.p. for enpassant moves.

### ISSUE THREAD

**Issue by Tilps** [notnil/chess#20]
As best I can tell, this is nonstandard.  So while decode can probably support it, encode should not output it.

**Comment by notnil** [comment]
I based the implementation off Wikipedia https://en.wikipedia.org/wiki/Algebraic_notation_(chess)#Captures.  Is there a competing source where this is documented?  Or compelling examples of it not being standard?

**Comment by notnil** [comment]
From https://chessprogramming.wikispaces.com/Algebraic+Chess+Notation:

En passant
The PGN-Standard does not require En passant captures have any special notation, and is written as if the captured pawn were on the capturing pawn's destination square.FIDE states the redundant move suffix "e.p." optional (after 1 July 2014) [11].

In the case of an ‘en passant’ capture, ‘e.p.’ may be appended to the notation.

**Comment by Tilps** [comment]
The PGN standard itself appears to makes no mention of it directly - it is in the FIDE as an 'option'. Wikipedia lists it as 'optional'.
Our (lczero) experience using the output of notnil/Chess is that the PGN renderer we use for our website does not understand it.
Someone writing a PGN parser just having read the PGN standard would probably fail to parse it.

I think the best thing to do is to not output it, but accept it on input.
Or alternatively have an encoder option to enable/disable it for output, but always accept on input.

**Comment by notnil** [comment]
@Tilps agreed.  Ill work on this.

**Comment by notnil** [comment]
Fixed in e1f1251d9c219338d8e43449ce2e059c013beb7d
