### ISSUE TITLE
Exporting methods in notnil/chess

### ISSUE THREAD

**Issue by kgigitdev** [notnil/chess#22]
Hi there!

I'm the author of kgigitdev/godgt, which I'm currently rewriting (not uploaded yet) to use your excellent library for legal move generation.

godgt is a command line utility to record games from DGT's electronic chess boards.

I was wondering if you would be open to exporting some of the currently non-exported methods in your library.

The DGT board generates low-level piece events ("e4 is now empty", "d5 now contains a white pawn"), which due to the speed and order in which the squares are scanned, you can sometimes receive out of order.

My (probably inefficient) technique is therefore to ask for a complete board dump every time I receive an event, then compare that to every legal next position from the most recently accepted legal move.

One big problem I have is sliding piece moves. For example, when executing a "Bb5" move, a player might slide the bishop over d2, e3 and c4, and if the board happens to scan the piece in that position, then Bd3/Be4/Bd4 becomes the accepted move, and the later "Bb5" is rejected as being an invalid move (because the same player is seemingly playing twice).

One workaround might be to store the previous game state (the state immediately before the most recently accepted legal move) and also see if the new position is a legal move in that  game state as well.

But that approach requires the ability to copy a game object. Game does goes have an unexported copy() method, but that's obviously not available.

There are a handful of other methods that are in a "would be nice to export" category, but which can be worked around. I can't recall them at the moment.

If you're open to such changes, let me know, and I'll see if I can get together a PR.

**Comment by notnil** [comment]
Yeah I ran into similar problems when building a chess bot.  I tend to be conservative about what I export so I don't have to break people's code later.  I am definitely open to facilitating your use cases.  If you want to make an PR I will definitely take a look.

**Comment by notnil** [comment]
Just saw https://github.com/notnil/chess/pull/23, reviewing

**Comment by notnil** [comment]
Merged
