### ISSUE TITLE
Implement BinaryMarshaler / BinaryUnmarshaler

### ISSUE THREAD

**Issue by neofight** [notnil/chess#36]
It would be good to implement the BinaryMarshaler / BinaryUnmarshaler interfaces for game, position & moves for the efficient storage / transmission of data. If you are happy with the idea, I'd be happy to have a go at implementing it.

**Comment by notnil** [comment]
Agreed.  Sure.  Give it a shot!

**Comment by notnil** [comment]
Added in #67
