### ISSUE TITLE
Implement UCI communication

### ISSUE THREAD

**Issue by ghost** [notnil/chess#40]
Implementing UCI communication for chess engines would be a great improvement. Could be worth adding it if possible.

**Comment by MelleKoning** [comment]
Agreed.
Please see https://github.com/notnil/chess/pull/44

**Comment by notnil** [comment]
I'm not sure this belongs in the same package.  If you get a stable version that utilizes this repo I can link to it from the README (similar to notnil/chessimg)

**Comment by MelleKoning** [comment]
Hi @notnil 
I agree packages should remain focused. Actually I wonder why chessimage is not just part of the same repository but than separated as golang package with a folder structure?

Anyway, have an example ucichessplayer package setup now, that depends on notnil/chess over here:
https://github.com/MelleKoning/ucichessplayer

**Comment by notnil** [comment]
@MelleKoning the reason I separated it was because of the difference in dependencies.  chess doesn't have any while chessimg does.  Go's dependency management has come a long way since when I started and I would consider subpackages now such as chess/image and chess/uci.  Do you want to create a branch as a subpackage and see how that looks?

**Comment by ipratt-code** [comment]
I think that would work.
Sorry for barging in, but I am writing a chess engine for Lichess. The only good way to accomplish this is to use pre-built modules that require UCI implementation, or make my own.
I think that a submodule for UCI would be beneficial to people like myself, making chess engines that require a UCI interface.

**Comment by notnil** [comment]
@MelleKoning I rejected the PR because of license issue but I think a UCI sub package definitely makes sense and would benefit others.  If I ever get around to it I would consider implementing one myself, but definitely happy to take contributions from the community.

**Comment by notnil** [comment]
I implemented a new subpackage.  Available in the 1.3 release: https://github.com/notnil/chess/releases/tag/v1.3.0
