### ISSUE TITLE
Parsing PGN with FEN tag

### ISSUE THREAD

**Issue by grmorozov** [notnil/chess#42]
Creation of a Game from PGN fails if it doesn't start from initial position. If FEN tag is present in PGN game description, it should be used to init a game.

Example.
Parsing of pgn with content:
```[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "N.N."]
[Black "N.N."]
[Result "1-0"]
[Annotator "T1R"]
[SetUp "1"]
[FEN "2r2rk1/pp1bqpp1/2nppn1p/2p3N1/1bP5/1PN3P1/PBQPPPBP/3R1RK1 w - - 0 1"]
[PlyCount "5"]
[EventType "swiss"]

1. Nd5 exd5 (1... hxg5 2. Nxe7+ Nxe7) 2. Bxf6 hxg5 3. Bxe7 1-0
```

returns error: `chess: pgn decode error chess: could not decode algebraic notation Nd5 for position rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 on move 1`

**Comment by grmorozov** [comment]
I submitted a PR: #43

**Comment by notnil** [comment]
Makes sense.  Thank you for your contribution.  Merged :)
