### ISSUE TITLE
Undoing a move pushed to chess.Game?

### ISSUE THREAD

**Issue by ArmanMaesumi** [notnil/chess#54]
I would like to use this Go library for an AlphaBeta pruning look ahead algorithm, but I don't understand how to neatly undo a move.  Say we pushed a move to a game like so

```
game := chess.NewGame()
moves := game.ValidMoves()
game.Move(moves[0])
```

How can we then undo the last move that was made?

**Comment by notnil** [comment]
You can use the position.Update method to move from valid moves directly and skip redundant validation:
https://godoc.org/github.com/notnil/chess#Position.Update

**Comment by notnil** [comment]
Hope this helped.
