### ISSUE TITLE
add test to threefoldRepetition

### ISSUE THREAD

**Issue by fabricede** [notnil/chess#56]
Here is a pull request I made to add more test in ThreeFoldRepetition in the file "game_test.go"

note that I also changed "repition" to "repetition"

// test Threefold repetition
func TestThreeFoldRepetition(t *testing.T) {
	testCases := []struct {
		name  string
		moves []string
		want  bool
	}{
		{"knight back home one times", []string{
			"Nf3", "Nf6", "Ng1", "Ng8",
		}, false},
		{"knight back home two times", []string{
			"Nf3", "Nf6", "Ng1", "Ng8",
			"Nf3", "Nf6", "Ng1", "Ng8",
		}, true},
		{"change king side castle right", []string{
			"e4", "e5", "Bc4", "Bc5",
			"Nf3", "Nf6",
			"Rf1", "Rf8", "Rh1", "Rh8",
			"Ng1", "Ng8",
			"Nf3", "Nf6", "Ng1", "Ng8",
		}, false},
		{"change en-passant right", []string{
			"e4", "e6", "e5", "d5",
			"Nf3", "Ne7", "Ng1", "Ng8",
			"Nf3", "Ne7", "Ng1", "Ng8",
		}, false},
		{"change side to move", []string{
			"e4", "e5",
			"Nf3", "Nf6", "Ng1", "Ng8",
			"Bb5", "Nf6", "Bc4", "Ng8",
			"Bf1",
		}, false},
	}
	for _, tc := range testCases {
		t.Run(fmt.Sprintf("%s=>%t", tc.name, tc.want), func(t *testing.T) {
			g := NewGame()
			for _, m := range tc.moves {
				if err := g.MoveStr(m); err != nil {
					t.Fatal(err)
				}
			}
			if err := g.Draw(ThreefoldRepetition); (tc.want == true && err != nil) || (tc.want == false && err == nil) {
				for _, pos := range g.Positions() {
					log.Println(pos.String())
				}
				t.Fatalf("%s - %d reps", err.Error(), g.numOfRepetitions())
			}
		})
	}
}

**Comment by notnil** [comment]
Please make an actual PR instead of issue with code.
