### ISSUE TITLE
PGN decode error: could not decode algebraic notation Rd1d2

### ISSUE THREAD

**Issue by AubreySLavigne** [notnil/chess#57]
I am parsing the [2013-01 database file from Lichess](https://database.lichess.org/standard/lichess_db_standard_rated_2013-01.pgn.bz2) (15Mb download), and encountered the following error:

`chess: pgn decode error chess: could not decode algebraic notation Rd1d2 for position 3r1rk1/1p1bqp2/p1pR1p1p/8/4P3/P4B2/1PP1QPP1/3R3K w - - 2 22 on move 22`

[FEN on Lichess](https://lichess.org/editor/3r1rk1/1p1bqp2/p1pR1p1p/8/4P3/P4B2/1PP1QPP1/3R3K_w_-_-_0_1)

The typical short notation would be `R1d2`, which is acceptable without error, but the long form error not accepted.

**How to Reproduce**

PGN:

```
[Event "Rated Blitz game"]
[Site "https://lichess.org/9opx3qh7"]
[White "adamsrj"]
[Black "hamiakaz"]
[Result "0-1"]
[UTCDate "2012.12.31"]
[UTCTime "23:02:48"]
[WhiteElo "1522"]
[BlackElo "1428"]
[WhiteRatingDiff "-14"]
[BlackRatingDiff "+14"]
[ECO "A40"]
[Opening "Englund Gambit Complex: Hartlaub-Charlick Gambit"]
[TimeControl "180+5"]
[Termination "Normal"]

1. d4 e5 2. dxe5 d6 3. exd6 Bxd6 4. Nf3 Nf6 5. Nc3 O-O 6. a3 Nc6 7. e3 a6 8. Be2 h6 9. O-O Ne5 10. Bd2 Nxf3+ 11. Bxf3 Be5 12. Rc1 c6 13. Qe2 Qd6 14. Rfd1 Bxh2+ 15. Kh1 Be5 16. e4 Bxc3 17. Bxc3 Qe6 18. Rd3 Bd7 19. Rcd1 Rad8 20. Bxf6 gxf6 21. Rd6 Qe7 22. Rd1d2 Be6 23. Rxd8 Rxd8 24. Rxd8+ Qxd8 25. c4 Qd4 26. c5 Qxc5 27. Qd2 f5 28. exf5 Bxf5 29. Qxh6 Bg6 30. Be4 Bxe4 31. Qh4 Bg6 32. Qd8+ Kg7 33. Qc7 b5 34. b4 Qc1+ 35. Kh2 Qxa3 36. Qe5+ Kg8 37. Qe8+ Kg7 38. Qxc6 Qxb4 39. Qxa6 Qh4+ 40. Kg1 b4 41. Qa1+ Qf6 42. Qa4 Qc3 43. f3 b3 44. Qa3 Qc2 45. Kh2 b2 0-1
```

I've confirmed the test failed by adding this line to `assets/valid_notation_tests.json` :

```
{
    "pos1" : "3r1rk1/1p1bqp2/p1pR1p1p/8/4P3/P4B2/1PP1QPP1/3R3K w - - 2 22",
    "pos2" : "3r1rk1/1p1bqp2/p1pR1p1p/8/4P3/P4B2/1PPRQPP1/7K b - - 3 22",
    "algText" : "R1d2",
    "longAlgText" : "Rd1d2",
    "description" : "https://lichess.org/editor/3r1rk1/1p1bqp2/p1pR1p1p/8/4P3/P4B2/1PP1QPP1/3R3K_w_-_-_2_22"
}    
```

Test Output:

```
--- FAIL: TestValidDecoding (0.01s)
    --- FAIL: TestValidDecoding/https://lichess.org/editor/3r1rk1/1p1bqp2/p1pR1p1p/8/4P3/P4B2/1PPRQPP1/7K_w_-_-_2_22 (0.00s)
        notation_test.go:45: starting from board

             A B C D E F G H
            8- - - ♜ - ♜ ♚ -
            7- ♟ - ♝ ♛ ♟ - -
            6♟ - ♟ ♖ - ♟ - ♟
            5- - - - - - - -
            4- - - - ♙ - - -
            3♙ - - - - ♗ - -
            2- ♙ ♙ - ♕ ♙ ♙ -
            1- - - ♖ - - - ♔

             expected move to be valid error - chess: failed to decode long algebraic notation text "Rd1d2" for position 3r1rk1/1p1bqp2/p1pR1p1p/8/4P3/P4B2/1PP1QPP1/3R3K w - - 2 22 h1g1,h1h2,e2e1,e2f1,e2d2,e2d3,e2e3,e2c4,e2b5,e2a6,d1a1,d1b1,d1c1,d1e1,d1f1,d1g1,d1d2,d1d3,d1d4,d1d5,d6d2,d6d3,d6d4,d6d5,d6c6,d6e6,d6f6,d6d7,f3g4,f3h5,b2b3,b2b4,c2c3,c2c4,g2g3,g2g4,a3a4,e4e5
FAIL
exit status 1
FAIL    github.com/notnil/chess 2.767s
```

**Comment by AubreySLavigne** [comment]
If you would like, I can look into this a bit further.

**Comment by AubreySLavigne** [comment]
I've found what is happening.

While the algorithm is named "LongAlgebraicNotation", it currently doesn't accept the form described [here (Wikipedia)](https://en.wikipedia.org/wiki/Algebraic_notation_(chess)#Long_algebraic_notation). Instead, it expects Universal Chess Interface, as described [here (also Wikipedia)](https://en.wikipedia.org/wiki/Universal_Chess_Interface).

| LAN | UCI |
|---|---|
| `Rd1d2` | `d1d2` |
| `Qc3c5+` | `c3c5` |
| `a7b8=Q#` | `a7b8q` |

Easiest resolution seems to be converting the LAN to UCI at the start of the function, then letting the rest proceed as usual.

**Comment by notnil** [comment]
@AubreySLavigne looks like you are correct.  Maybe it makes more sense to support both notations LongAlgebraicNotation and UCINotation?

**Comment by AubreySLavigne** [comment]
I agree that would be for the best. I mostly took my 2-in-1 approach to maintain backwards compatibility if anything else is relying on that functionality. I can look into expanding that in a day or two, and will get back to you shortly.

**Comment by AubreySLavigne** [comment]
UCINotation has been split out into another "algorithm struct", and all current tests are passing.

I have one more test to write, related to the Lichess PGNs (the problem that spurred this issue in the first place)

**Comment by notnil** [comment]
Weird so I ended up parsing that file myself and it appears that lichess switches notation mid game?  I think this is just an error in the lichess DB.  When I put it into the lichess explorer the PGN is different: 

https://lichess.org/9opx3qh7#43

**Comment by notnil** [comment]
I think the problem here is that lichess (at least in that file) disambiguates moves with too much information.   The PGN is in algebraic notation but is written incorrectly `Rd1d2` should be `R1d2`.  I think the fix here is to make the PGN parser more permissive because it can be determined what is intended.

**Comment by notnil** [comment]
^ That was indeed the problem.  To fix it I checked multiple notation types using a multidecoder in the PGN parser.  I also throw in Scanner while I was at it to parse the large lichess DB files.  The implemented differed enough that I didn't take this PR but thank for you finding it and proposing an implementation.
