### ISSUE TITLE
List valid moves for the non "current" color?

### ISSUE THREAD

**Issue by jpleau** [notnil/chess#60]
Hi.

Writing a UI using this library, and I'm running into a smallish issue, maybe you have a solution for me!

In my game, whenever you drag one of your pieces around, it will highlight the squares you can move it to.

When it's the opponent's turn, I can still drag my pieces around (but not drop them obviously), and I'd like to still highlight the possible moves for that piece while my opponent is thinking.

Using the previous position works great, however I can't get the "new" valid moves from the piece I just moved. It'll be easier to show screenshots of what I mean.

This is the position before I make move, you can see the white king is being dragged around and the squares where I can move my king are highlighted

https://jpleau.ca/before_move.png

This is the position after I move (and it's now my opponent's turn). My king is being dragged around. I would like to get the possible moves for my king, but ValidMoves() only lists moves for black until they make their move.

https://jpleau.ca/after_move.png

Is there something I can do to list the valid moves for the opposite color of Position().Turn() ? I was thinking being able to call Position().Update(nil) to simulate a no-op move for the current player, and so I could use that position to list the valid moves I need. I have no idea of the feasibility of this, as adding invalid moves could break things...

Do you have a suggestion for me ?

Thanks !

**Comment by jpleau** [comment]
I think this is what python-chess is doing:

https://python-chess.readthedocs.io/en/latest/core.html#chess.Move.null

So a `null` move just lets you "skip" a turn, which is what I would need in this case !

**Comment by jpleau** [comment]
I think using Position().Update(&Move{}) does the trick here !

**Comment by notnil** [comment]
Glad you figured out a solution!
