### ISSUE TITLE
Chess Game using notnil/chess

### ISSUE THREAD

**Issue by tmountain** [notnil/chess#66]
Hi,

I'm writing to extend a huge thanks for this module and to let you know that I've just released a terminal based chess game that makes heavy use of notnil/chess. Your module was hugely helpful in permitting me to focus on the core functionality of the game rather than dealing with all of the idiosyncrasies of chess rules. Thank you!

[https://github.com/tmountain/uchess](https://github.com/tmountain/uchess)

**Comment by tmountain** [comment]
BTW, I added an acknowledgement to your module in a "Special Thanks" section in my project's README.md.

**Comment by notnil** [comment]
Very cool!  I will have to check this out!  I have definitely reached for something like this when playing around in the terminal.  And great terminal UI!

I just added UCI for this lib as well btw if its easier to use the notnil/chess types but https://github.com/freeeve/uci seems like a very similar implementation.
