### ISSUE TITLE
Which Piece has moved?

### ISSUE THREAD

**Issue by jojomi** [notnil/chess#83]
I am trying to find the first queen move in a game. Looping over the Move slice returned by `game.Moves()` seemed like a good idea, but I don't find a way to correlate the move to the piece being on the start square before or the target square after it was executed. Is there a good way to do this using the Positions data?

Thank you for any pointer to the right direction here :)

**Comment by Christoph-Harms** [comment]
If you are talking about a standard game (i.e. started from starting position), just look for the first move where `s1` is d1 (for white) or d8 (for black).

**Comment by jojomi** [comment]
Thanks for the idea, I did not think about this trick before.

But I think it is not accurate:
1. e4 d5 2. e5 Bg4 3. Nc3 Bxd1 4. Nxd1 e6 5. Ne3

The last move is the first (white) move to originate from e1 while it is not a queen move.

**Comment by notnil** [comment]
https://go.dev/play/p/yW1HiQVe7Ix

**Comment by jojomi** [comment]
That looks good, thank you very much!
